apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      name: customer-service
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-srv
          image: franco148/microservice-demo-customer-service:2.1-K8S
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
