apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-srv
  labels:
    app: customer-srv
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer-srv
          image: franco148/customer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer-srv