server:
  port: 9292

spring:
  application:
    name: notification-service
  datasource:
    password: password01!
    username: fullstack
    url: jdbc:postgresql://172.18.0.2:5432/notification-svr-db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0  # Sample all requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans