services:
  ms-db:
    container_name: ms-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: fullstack
      POSTGRES_PASSWORD: password01!
      PGDATA: /data/postgres
    volumes:
      - ms-postgres:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - ms-postgres-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fullstack" ]
      interval: 10s
      retries: 5

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    depends_on:
#      - db
#    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ms-demo-network

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ms-demo-network

  eureka-server:
    image: franco148/microservice-demo-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-demo-network
    depends_on:
      - zipkin

  api-gateway:
    image: franco148/microservice-demo-api-gateway-service:latest
    container_name: api-gateway
    ports:
      - "9393:9393"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-demo-network
    depends_on:
      - zipkin
      - eureka-server

  customer-server:
    image: franco148/microservice-demo-customer-service:latest
    container_name: customer-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-demo-network
      - ms-postgres-network
    depends_on:
      ms-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started

  fraud-server:
    image: franco148/microservice-demo-fraud-service:latest
    container_name: fraud-service
    ports:
      - "9191:9191"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-demo-network
      - ms-postgres-network
    depends_on:
      ms-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started

  notification-server:
    image: franco148/microservice-demo-notification-service:latest
    container_name: notification-service
    ports:
      - "9292:9292"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-demo-network
      - ms-postgres-network
    depends_on:
      ms-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started

networks:
  ms-postgres-network:
    driver: bridge
  ms-demo-network:
    driver: bridge

volumes:
  ms-postgres:
  pgadmin: