server:
  port: 9090

spring:
  application:
    name: customer-service
  datasource:
    password: password01!
    username: fullstack
    url: jdbc:postgresql://ms-postgres:5432/customer-svr-db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false # Before kubernetes

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0  # Sample all requests
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    file: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"