apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-srv
  labels:
    app: notification-srv
spec:
  replicas: 1
  template:
    metadata:
      name: notification-srv
      labels:
        app: notification-srv
    spec:
      containers:
        - name: notification-srv
          image: franco148/microservice-demo-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9292
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification-srv